# Generated by Django 5.0.6 on 2024-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userAvatar', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('imageUrl', models.URLField()),
            ],
        ),
    ]
