# Generated by Django 5.0.6 on 2024-05-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PBS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userAvatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='blog_count',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
