# Generated by Django 5.0.6 on 2024-05-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blogId',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='blog_count',
            field=models.IntegerField(default=0),
        ),
    ]
