# Generated by Django 5.0.6 on 2024-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBS', '0002_remove_post_blog_count_remove_post_useravatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userAvatar',
            field=models.URLField(default='http://example.com/avatar.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=321, max_length=200),
            preserve_default=False,
        ),
    ]
